tcp:
  port: 12345
  bind: "0.0.0.0"

mqtt:
  broker: "tcp://localhost:1883"
  client_id: "tcp_bridge"
  topics:
    - "device/+"
    - "control/#"
  topic_template: "device/{packet_name}/{field_name}"
  payload_template: "{value}"

logging:
  level: "debug"

packet_def: "packets.yaml"
